import type { ReadonlyDeep, PluginConfig, PluginSetting } from '@nixcord/shared';
import {
  isBoolean,
  isNumber,
  isString,
  isNull,
  isArray,
  isObject,
  isNestedConfig,
  INTEGER_STRING_PATTERN,
  NIX_ENUM_TYPE,
  NIX_TYPE_FLOAT,
  NIX_TYPE_INT,
} from '@nixcord/shared';
import { toNixIdentifier } from './identifier.js';

export type PluginCategory = 'shared' | 'vencord' | 'equicord';

/** JSON representation of a single plugin setting for the Nix-side builder. */
export interface PluginSettingJson {
  type: string;
  default?: unknown;
  description?: string;
  enumValues?: (string | number | boolean)[];
  example?: string;
}

/** JSON representation of a plugin for the Nix-side builder. */
export interface PluginJson {
  description: string;
  settings: Record<string, PluginSettingJson | PluginJson>;
}

const categoryLabel = (category: PluginCategory): string => {
  switch (category) {
    case 'shared':
      return ' (Shared between Vencord and Equicord)';
    case 'vencord':
      return ' (Vencord-only)';
    case 'equicord':
      return ' (Equicord-only)';
  }
};

const buildEnumMappingDescription = (
  enumValues: readonly (string | number | boolean)[],
  enumLabels?: ReadonlyDeep<Record<string, string> & Partial<Record<number, string>>>
): string | undefined => {
  if (!enumLabels) return undefined;

  const integerValues = enumValues.filter(isNumber);
  if (integerValues.length === 0) return undefined;

  const mappings = integerValues
    .map((intValue) => ({
      value: intValue,
      label: enumLabels[intValue] ?? enumLabels[String(intValue)],
    }))
    .filter((item): item is { value: number; label: string } => typeof item.label === 'string')
    .map((item) => `${item.value} = ${item.label}`);

  return mappings.length === 0 ? undefined : mappings.join(', ');
};

const resolveDefault = (setting: Readonly<PluginSetting>): unknown | undefined => {
  if (setting.default === undefined) return undefined;
  if (setting.default === null) return null;

  const type = setting.type;
  const val = setting.default;

  // Float integers need to stay as floats (e.g. 1 -> 1.0)
  if (isNumber(val) && type === NIX_TYPE_FLOAT && Number.isInteger(val))
    return { __nixRaw: val.toFixed(1) };

  // String integers used as int defaults (e.g. BigInt IDs)
  if (type === NIX_TYPE_INT && isString(val) && INTEGER_STRING_PATTERN.test(val))
    return { __nixRaw: val };

  if (
    isString(val) ||
    isNumber(val) ||
    isBoolean(val) ||
    isNull(val) ||
    isArray(val) ||
    (isObject(val) && !isNull(val))
  )
    return val;

  return undefined;
};

const buildSettingDescription = (setting: Readonly<PluginSetting>): string | undefined => {
  if (!setting.description) return undefined;

  const isIntegerEnum = setting.enumValues?.every(isNumber) && setting.type === NIX_ENUM_TYPE;
  if (!isIntegerEnum || !setting.enumValues) return setting.description;

  const mapping = buildEnumMappingDescription(setting.enumValues, setting.enumLabels);
  return mapping !== undefined
    ? `${setting.description}\n\nValues: ${mapping}`
    : setting.description;
};

export const generateSettingJson = (
  setting: Readonly<PluginSetting>,
  _category?: PluginCategory
): PluginSettingJson => {
  const json: PluginSettingJson = { type: setting.type };

  if (setting.type?.includes('enum') && setting.enumValues) {
    json.enumValues = [...setting.enumValues];
  }

  const resolvedDefault = resolveDefault(setting);
  if (resolvedDefault !== undefined) json.default = resolvedDefault;

  const description = buildSettingDescription(setting);
  if (description) json.description = description;

  if (setting.example && !setting.description?.includes(setting.example)) {
    json.example = setting.example;
  }

  return json;
};

export const generatePluginJson = (
  _pluginName: string,
  config: Readonly<PluginConfig>,
  category?: PluginCategory
): PluginJson => {
  const settings: Record<string, PluginSettingJson | PluginJson> = {};

  for (const [, setting] of Object.entries(config.settings)) {
    const nixName = toNixIdentifier(setting.name);
    if (setting.name === 'enable') continue; // enable is always auto-generated by Nix side
    if (isNestedConfig(setting)) {
      settings[nixName] = generatePluginJson(setting.name, setting as PluginConfig, category);
    } else {
      settings[nixName] = generateSettingJson(setting as PluginSetting, category);
    }
  }

  const description = category
    ? (config.description ?? '') + categoryLabel(category)
    : (config.description ?? '');

  return { description, settings };
};

export const generatePluginModule = (
  plugins: ReadonlyDeep<Record<string, PluginConfig>>,
  category?: PluginCategory
): string => {
  const output: Record<string, PluginJson> = {};

  const sortedKeys = Object.keys(plugins).sort((a, b) =>
    toNixIdentifier(a).localeCompare(toNixIdentifier(b))
  );

  for (const pluginName of sortedKeys) {
    const config = plugins[pluginName];
    if (!config) continue;
    output[toNixIdentifier(pluginName)] = generatePluginJson(pluginName, config, category);
  }

  return JSON.stringify(output, null, 2);
};
