# This file is auto-generated by scripts/generate-plugin-options
# DO NOT EDIT this file directly; instead update the generator

{
  AllCallTimers = "CallTimer";
  AmITyping = "TypingTweaks";
  QuestCompleter = "Questify";
}
