# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{
  renames = {
  };
  removals = {
    absRPC = {
      date = "2026-03-07";
    };
    betterUserArea = {
      date = "2026-03-01";
    };
    dmKeeper = {
      date = "2026-03-02";
    };
    favEmojiFirst = {
      date = "2026-02-11";
    };
    gensokyoRadioRPC = {
      date = "2026-03-07";
    };
    iRememberYou = {
      date = "2026-03-07";
    };
    listenBrainzRPC = {
      date = "2026-03-07";
    };
    noAppsAllowed = {
      date = "2026-03-07";
    };
    tosuRPC = {
      date = "2026-03-07";
    };
    translatePlus = {
      date = "2026-03-07";
    };
    triviaAI = {
      date = "2026-03-07";
    };
    unreadBadgeCount = {
      date = "2026-03-07";
    };
  };
  settingRenames = {
    fontLoader = {
      applyOnClodeBlocks = "applyOnCodeBlocks";
    };
    globalBadges = {
      showRa1ncord = "showRaincord";
    };
    noBlockedMessages = {
      applyToIgnoredUsers = "alsoHideIgnoredUsers";
      ignoreMessages = "disableNotifications";
    };
    platformIndicators = {
      badges = "profiles";
    };
  };
}
