# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{
  renames = {
  };
  removals = {
  };
  settingRenames = {
    fontLoader = {
      applyOnClodeBlocks = "applyOnCodeBlocks";
    };
    globalBadges = {
      showRa1ncord = "showRaincord";
    };
    noBlockedMessages = {
      applyToIgnoredUsers = "alsoHideIgnoredUsers";
      ignoreMessages = "disableNotifications";
    };
    platformIndicators = {
      badges = "profiles";
    };
  };
}
