# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  base = [
    "programs"
    "nixcord"
    "config"
    "plugins"
  ];
in
{
  imports = [
    # AllCallTimers -> CallTimer
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "allCallTimers"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "allCallTimers"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "enable"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "format"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "format"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "showRoleColor"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "showRoleColor"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "showSeconds"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "showSeconds"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "showWithoutHover"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "showWithoutHover"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "trackSelf"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "trackSelf"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "allCallTimers"
          "watchLargeGuilds"
        ]
      )
      (
        base
        ++ [
          "callTimer"
          "watchLargeGuilds"
        ]
      )
    )

    # AmITyping -> TypingTweaks
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "AmITyping"
          "alternativeFormatting"
        ]
      )
      (
        base
        ++ [
          "typingTweaks"
          "alternativeFormatting"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "AmITyping"
          "amITyping"
        ]
      )
      (
        base
        ++ [
          "typingTweaks"
          "amITyping"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "AmITyping"
          "enable"
        ]
      )
      (
        base
        ++ [
          "typingTweaks"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "AmITyping"
          "showAvatars"
        ]
      )
      (
        base
        ++ [
          "typingTweaks"
          "showAvatars"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "AmITyping"
          "showRoleColors"
        ]
      )
      (
        base
        ++ [
          "typingTweaks"
          "showRoleColors"
        ]
      )
    )

    # QuestCompleter -> Questify
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "claimedSubsort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "claimedSubsort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "completeAchievementQuestsInBackground"
        ]
      )
      (
        base
        ++ [
          "questify"
          "completeAchievementQuestsInBackground"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "completeGameQuestsInBackground"
        ]
      )
      (
        base
        ++ [
          "questify"
          "completeGameQuestsInBackground"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "completeVideoQuestsInBackground"
        ]
      )
      (
        base
        ++ [
          "questify"
          "completeVideoQuestsInBackground"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableFriendsListActiveNowPromotion"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableFriendsListActiveNowPromotion"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableMembersListActivelyPlayingIcon"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableMembersListActivelyPlayingIcon"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsBadgeOnUserProfiles"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsBadgeOnUserProfiles"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsDirectMessagesTab"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsDirectMessagesTab"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsDiscoveryTab"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsDiscoveryTab"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsEverything"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsEverything"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsFetchingQuests"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsFetchingQuests"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsGiftInventoryRelocationNotice"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsGiftInventoryRelocationNotice"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsPageSponsoredBanner"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsPageSponsoredBanner"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "disableQuestsPopupAboveAccountPanel"
        ]
      )
      (
        base
        ++ [
          "questify"
          "disableQuestsPopupAboveAccountPanel"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "enable"
        ]
      )
      (
        base
        ++ [
          "questify"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "expiredSubsort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "expiredSubsort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "fetchingQuestsAlert"
        ]
      )
      (
        base
        ++ [
          "questify"
          "fetchingQuestsAlert"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "fetchingQuestsAlertVolume"
        ]
      )
      (
        base
        ++ [
          "questify"
          "fetchingQuestsAlertVolume"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "fetchingQuestsInterval"
        ]
      )
      (
        base
        ++ [
          "questify"
          "fetchingQuestsInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "ignoredQuestIDs"
        ]
      )
      (
        base
        ++ [
          "questify"
          "ignoredQuestIDs"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "ignoredQuestProfile"
        ]
      )
      (
        base
        ++ [
          "questify"
          "ignoredQuestProfile"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "ignoredSubsort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "ignoredSubsort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "lastQuestPageFilters"
        ]
      )
      (
        base
        ++ [
          "questify"
          "lastQuestPageFilters"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "lastQuestPageSort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "lastQuestPageSort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "makeMobileQuestsDesktopCompatible"
        ]
      )
      (
        base
        ++ [
          "questify"
          "makeMobileQuestsDesktopCompatible"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "notifyOnQuestComplete"
        ]
      )
      (
        base
        ++ [
          "questify"
          "notifyOnQuestComplete"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "onQuestsPage"
        ]
      )
      (
        base
        ++ [
          "questify"
          "onQuestsPage"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonBadgeColor"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonBadgeColor"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonDisplay"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonLeftClickAction"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonLeftClickAction"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonMiddleClickAction"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonMiddleClickAction"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonRightClickAction"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonRightClickAction"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questButtonUnclaimed"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questButtonUnclaimed"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questRewardIncludeCollectibles"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questRewardIncludeCollectibles"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questRewardIncludeInGame"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questRewardIncludeInGame"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questRewardIncludeNitroCode"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questRewardIncludeNitroCode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questRewardIncludeOrbs"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questRewardIncludeOrbs"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "questRewardIncludeRewardCode"
        ]
      )
      (
        base
        ++ [
          "questify"
          "questRewardIncludeRewardCode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "rememberQuestPageFilters"
        ]
      )
      (
        base
        ++ [
          "questify"
          "rememberQuestPageFilters"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "rememberQuestPageSort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "rememberQuestPageSort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "reorderQuests"
        ]
      )
      (
        base
        ++ [
          "questify"
          "reorderQuests"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsClaimed"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsClaimed"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsExpired"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsExpired"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsGradient"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsGradient"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsIgnored"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsIgnored"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsPreload"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsPreload"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "restyleQuestsUnclaimed"
        ]
      )
      (
        base
        ++ [
          "questify"
          "restyleQuestsUnclaimed"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "resumeQuestIDs"
        ]
      )
      (
        base
        ++ [
          "questify"
          "resumeQuestIDs"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "triggerQuestsRerender"
        ]
      )
      (
        base
        ++ [
          "questify"
          "triggerQuestsRerender"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "unclaimedSubsort"
        ]
      )
      (
        base
        ++ [
          "questify"
          "unclaimedSubsort"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "questCompleter"
          "unclaimedUnignoredQuests"
        ]
      )
      (
        base
        ++ [
          "questify"
          "unclaimedUnignoredQuests"
        ]
      )
    )

    # Setting renames: fontLoader
    (lib.modules.doRename {
      from = base ++ [
        "fontLoader"
        "applyOnClodeBlocks"
      ];
      to = base ++ [
        "fontLoader"
        "applyOnCodeBlocks"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: globalBadges
    (lib.modules.doRename {
      from = base ++ [
        "globalBadges"
        "showRa1ncord"
      ];
      to = base ++ [
        "globalBadges"
        "showRaincord"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: platformIndicators
    (lib.modules.doRename {
      from = base ++ [
        "platformIndicators"
        "badges"
      ];
      to = base ++ [
        "platformIndicators"
        "profiles"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Removed: absRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.absRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'absRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.absRPC.enable or false)
            "Plugin 'absRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: betterUserArea
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.betterUserArea = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'betterUserArea' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.betterUserArea.enable or false)
            "Plugin 'betterUserArea' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: dmKeeper
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.dmKeeper = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'dmKeeper' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.dmKeeper.enable or false)
            "Plugin 'dmKeeper' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: favEmojiFirst
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.favEmojiFirst = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'favEmojiFirst' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.favEmojiFirst.enable or false)
            "Plugin 'favEmojiFirst' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: gensokyoRadioRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.gensokyoRadioRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'gensokyoRadioRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.gensokyoRadioRPC.enable or false)
            "Plugin 'gensokyoRadioRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: iRememberYou
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.iRememberYou = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'iRememberYou' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.iRememberYou.enable or false)
            "Plugin 'iRememberYou' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: listenBrainzRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.listenBrainzRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'listenBrainzRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.listenBrainzRPC.enable or false)
            "Plugin 'listenBrainzRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: noAppsAllowed
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.noAppsAllowed = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'noAppsAllowed' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.noAppsAllowed.enable or false)
            "Plugin 'noAppsAllowed' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: tosuRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.tosuRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'tosuRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.tosuRPC.enable or false)
            "Plugin 'tosuRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: translatePlus
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.translatePlus = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'translatePlus' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.translatePlus.enable or false)
            "Plugin 'translatePlus' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: triviaAI
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.triviaAI = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'triviaAI' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.triviaAI.enable or false)
            "Plugin 'triviaAI' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: unreadBadgeCount
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.unreadBadgeCount = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'unreadBadgeCount' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.unreadBadgeCount.enable or false)
            "Plugin 'unreadBadgeCount' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

  ];
}
