# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  base = [
    "programs"
    "nixcord"
    "config"
    "plugins"
  ];
in
{
  imports = [
    # Setting renames: fontLoader
    (lib.modules.doRename {
      from = base ++ [
        "fontLoader"
        "applyOnClodeBlocks"
      ];
      to = base ++ [
        "fontLoader"
        "applyOnCodeBlocks"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: globalBadges
    (lib.modules.doRename {
      from = base ++ [
        "globalBadges"
        "showRa1ncord"
      ];
      to = base ++ [
        "globalBadges"
        "showRaincord"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: platformIndicators
    (lib.modules.doRename {
      from = base ++ [
        "platformIndicators"
        "badges"
      ];
      to = base ++ [
        "platformIndicators"
        "profiles"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Removed: absRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.absRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'absRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.absRPC.enable or false)
            "Plugin 'absRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: betterUserArea
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.betterUserArea = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'betterUserArea' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.betterUserArea.enable or false)
            "Plugin 'betterUserArea' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: dmKeeper
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.dmKeeper = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'dmKeeper' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.dmKeeper.enable or false)
            "Plugin 'dmKeeper' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: favEmojiFirst
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.favEmojiFirst = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'favEmojiFirst' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.favEmojiFirst.enable or false)
            "Plugin 'favEmojiFirst' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: gensokyoRadioRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.gensokyoRadioRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'gensokyoRadioRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.gensokyoRadioRPC.enable or false)
            "Plugin 'gensokyoRadioRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: iRememberYou
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.iRememberYou = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'iRememberYou' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.iRememberYou.enable or false)
            "Plugin 'iRememberYou' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: listenBrainzRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.listenBrainzRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'listenBrainzRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.listenBrainzRPC.enable or false)
            "Plugin 'listenBrainzRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: noAppsAllowed
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.noAppsAllowed = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'noAppsAllowed' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.noAppsAllowed.enable or false)
            "Plugin 'noAppsAllowed' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: tosuRPC
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.tosuRPC = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'tosuRPC' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.tosuRPC.enable or false)
            "Plugin 'tosuRPC' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: translatePlus
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.translatePlus = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'translatePlus' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.translatePlus.enable or false)
            "Plugin 'translatePlus' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: triviaAI
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.triviaAI = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'triviaAI' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.triviaAI.enable or false)
            "Plugin 'triviaAI' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

    # Removed: unreadBadgeCount
    (
      { config, lib, ... }:
      {
        options.programs.nixcord.config.plugins.unreadBadgeCount = lib.mkOption {
          type = lib.types.anything;
          default = { };
          visible = false;
          description = "REMOVED: Plugin 'unreadBadgeCount' was removed upstream.";
        };
        config.warnings =
          lib.optional (config.programs.nixcord.config.plugins.unreadBadgeCount.enable or false)
            "Plugin 'unreadBadgeCount' has been removed upstream. Please remove it from your nixcord configuration. This shim will be removed soon.";
      }
    )

  ];
}
