name: Flake Checks

on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "modules/**"
      - "pkgs/**"
  push:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "modules/**"
      - "pkgs/**"
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 1

      - uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            extra-nix-path = nixpkgs=flake:github:NixOS/nixpkgs/nixos-25.11

      - name: Run flake checks
        run: nix flake check --print-build-logs
